### PR TITLE
Use serialization to save and load pairs of integrators and abstract kite models.

### PR DESCRIPTION
**Pull request by 1-Bart-1**
Each time the simulator is initialized with the same settings, the same integrator is found. This branch will load and save such pairs of integrators and abstract kite models, as this is way faster than calculating the integrator again and again.

```
integrator_history = load_history()
# normal code
integrator = KiteModels.init_sim!(kps4, stiffness_factor=0.04, prn=false, integrator_history=integrator_history)
# normal code
save_history(integrator_history)
```

When using integrator_history, KiteModels.init_sim! is 10x faster than whithout using integrator_history.

### CODE REVIEW

**Comment by ufechner7** [comment]
Is there any practical application where the time of executing `init_sim!()` limits the the overall performance?

**Comment by 1-Bart-1** [comment]
Yes, when automatically optimizing the KCU or when optimizing other control
methods, the kite has to be reset often. I am optimizing a neural network
for the kite, and have to reset the kite at the start of every episode. It
can also be useful when optimizing a PID controller using optimizing
methods. So in any situation where the simulation has to be reset often.

**Comment by 1-Bart-1** [comment]
found a bug, reset wasnt working properly

**Comment by ufechner7** [comment]
One remark: For the four point model I suggest a stiffness-factor of 0.5. This save some time.

**Pull request closed without merging**
